server:
  port: 8081
spring:
  datasource:
    username: root
    password: MyNewPass@123
    # password: root
    url: jdbc:mysql://192.168.0.109:3306/acg_authority?useSSL=true&serverTimezone=UTC
    # url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=true&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #redis连接
  redis:
    host: 192.168.0.109
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间（负数表示没有限制）
        max-wait: -1
        max-idle: 5
        #最小空闲
        min-idle: 0
  #nacos服务地址
  #cloud:
  #  nacos:
        #    discovery:
    #     server-addr: 192.168.0.109:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.acg.authority.pojo
logging:
  level:
    com:
      acg:
        authority:
          dao: debug
